### ISSUE TITLE
Show SD card info in debug window when app initially opens

### ISSUE THREAD

**Issue by aperezbios** [rabbitholecomputing/SCSI2SD#11]
For behavioral parity with the legacy app, please print out the log lines showing the detected SD card value when the app is initlally opened.

**Comment by gcasa** [comment]
Gregory Casamento  1:45 PM
The legacy util prints this…
1:45
01:44:42 PM: SCSI2SD Ready, firmware version 4.8.4
01:44:42 PM: SD Capacity (512-byte sectors): 62129152
SD CSD Register: 400e00325b590000edc87f800a4040c3
SD CID Register: 035344534333324780edcb4b9b0146db
1:45
One sec, let’s see what the new one does…

Alex Perez  1:45 PM
yep, that's what I want. The time would be good to restore

Gregory Casamento  1:47 PM
SD Capacity (512-byte sectors): 62129152
SD CSD Register: 40e0325b5900edc87f80a4040c3
SD CID Register: 35344534333324780edcb4b9b146db
1:47
You mean if the card is already attached?

Alex Perez  1:48 PM
I'd like it to print the ready line too. basically want this to be the same experience for people who have been using the original utility for years

Gregory Casamento  1:48 PM
ok

**Comment by gcasa** [comment]
2020-12-13 19:38:22 +0000: SCSI2SD Ready, firmware version 4.8.4
SD Capacity (512-byte sectors): 62129152
SD CSD Register: 40e0325b5900edc87f80a4040c3
SD CID Register: 35344534333324780edcb4b9b146db

**Comment by gcasa** [comment]
The above now shows.

**Comment by gcasa** [comment]
Closing, reopen if needed.
